#include "STD_TYPES.h"
 #include "UTILES.h"
 #include "GPIO.h"
 #include "SPI.h"
 #include "GPIO_CONFIG.h"
 #include "SPI_LOCAL.h"
#include "avr/delay.h"






  int main(void)
 {



 	//GPIO_INIT_PIN_DIRECTION(PORT_D,0,OUTPUT);
 	//GPIO_INIT_PIN_DIRECTION(PORT_D,0,OUTPUT);

 	// SET SPI SELECTIVE TO BE LOW AND INPUT TO ENABLE MASTER MODE

 	//GPIO_WRITE_PIN_VALUE(PORT_B,4,LOW);


 SPI_SlaveInit();

 GPIO_INIT_PIN_DIRECTION(PORT_B,4,INPUT);
 GPIO_INIT_PIN_DIRECTION(PORT_B,5,INPUT);
 GPIO_INIT_PIN_DIRECTION(PORT_B,6,OUTPUT);
 GPIO_INIT_PIN_DIRECTION(PORT_B,7,INPUT);



 	 	 	 	 	 // 			GPIO_WRITE_PIN_VALUE(PORT_B,6,GPIO_READ_PIN_VALUE(PORT_A,PIN1));//

 	 UINT8 X;

  	GPIO_INIT_PIN_DIRECTION(PORT_C,0,OUTPUT);
  	GPIO_INIT_PIN_DIRECTION(PORT_C,1,OUTPUT);
  	GPIO_INIT_PIN_DIRECTION(PORT_C,2,OUTPUT);
  	GPIO_INIT_PIN_DIRECTION(PORT_C,3,OUTPUT);
  	GPIO_INIT_PIN_DIRECTION(PORT_C,4,OUTPUT);
 	while(1)
 	{
 		X=SPI_SlaveReceive();

 			while(X==1)
 		{

 			GPIO_WRITE_PIN_VALUE(PORT_C,0,HIGH);
 			GPIO_WRITE_PIN_VALUE(PORT_C,1,HIGH);
 			GPIO_WRITE_PIN_VALUE(PORT_C,2,HIGH);
 			GPIO_WRITE_PIN_VALUE(PORT_C,3,HIGH);
 			GPIO_WRITE_PIN_VALUE(PORT_C,4,HIGH);
 			_delay_ms(10);
 			GPIO_WRITE_PIN_VALUE(PORT_C,0,LOW);
 			GPIO_WRITE_PIN_VALUE(PORT_C,1,LOW);
 			GPIO_WRITE_PIN_VALUE(PORT_C,2,LOW);
 			GPIO_WRITE_PIN_VALUE(PORT_C,3,LOW);
 			GPIO_WRITE_PIN_VALUE(PORT_C,4,LOW);
 			_delay_ms(10);

 			GPIO_WRITE_PIN_VALUE(PORT_C,0,HIGH);
 			_delay_ms(20);
 			GPIO_WRITE_PIN_VALUE(PORT_C,1,HIGH);
 			_delay_ms(20);
 			GPIO_WRITE_PIN_VALUE(PORT_C,2,HIGH);
 			_delay_ms(20);
 			GPIO_WRITE_PIN_VALUE(PORT_C,3,HIGH);
 			_delay_ms(20);
 			GPIO_WRITE_PIN_VALUE(PORT_C,4,HIGH);

 			GPIO_WRITE_PIN_VALUE(PORT_C,0,HIGH);
 			GPIO_WRITE_PIN_VALUE(PORT_C,1,HIGH);
 			GPIO_WRITE_PIN_VALUE(PORT_C,2,HIGH);
 			GPIO_WRITE_PIN_VALUE(PORT_C,3,HIGH);
 			GPIO_WRITE_PIN_VALUE(PORT_C,4,HIGH);
 			_delay_ms(20);
 			GPIO_WRITE_PIN_VALUE(PORT_C,0,HIGH);
 			GPIO_WRITE_PIN_VALUE(PORT_C,1,HIGH);
 			GPIO_WRITE_PIN_VALUE(PORT_C,2,HIGH);
 			GPIO_WRITE_PIN_VALUE(PORT_C,3,HIGH);
 			GPIO_WRITE_PIN_VALUE(PORT_C,4,HIGH);

 			GPIO_WRITE_PIN_VALUE(PORT_C,0,LOW);
 			GPIO_WRITE_PIN_VALUE(PORT_C,1,LOW);
 			GPIO_WRITE_PIN_VALUE(PORT_C,2,LOW);
 			GPIO_WRITE_PIN_VALUE(PORT_C,3,LOW);
 			GPIO_WRITE_PIN_VALUE(PORT_C,4,LOW);

 			GPIO_WRITE_PIN_VALUE(PORT_C,0,HIGH);
 			_delay_ms(20);
 			GPIO_WRITE_PIN_VALUE(PORT_C,0,LOW);
 			GPIO_WRITE_PIN_VALUE(PORT_C,1,HIGH);
 			_delay_ms(20);
 			GPIO_WRITE_PIN_VALUE(PORT_C,1,LOW);
 			GPIO_WRITE_PIN_VALUE(PORT_C,2,HIGH);
 			_delay_ms(20);
 			GPIO_WRITE_PIN_VALUE(PORT_C,2,LOW);
 			GPIO_WRITE_PIN_VALUE(PORT_C,3,HIGH);
 			_delay_ms(20);
 			GPIO_WRITE_PIN_VALUE(PORT_C,3,LOW);
 			GPIO_WRITE_PIN_VALUE(PORT_C,4,HIGH);
 			_delay_ms(20);
 			GPIO_WRITE_PIN_VALUE(PORT_C,4,LOW);
 			_delay_ms(40);


 		}
 	}

 return 0;

 }

