/*
 * GPIO.h
 *
 *  Created on: Aug 27, 2021
 *      Author: ibrah
 */

#ifndef GPIO_H_
#define GPIO_H_

void GPIO_INIT_PORT_DIRECTION(UINT8 PORT , UINT8 DIRECTION);
void GPIO_WRITE_PORT_VALUE(UINT8 PORT , UINT8 VALUE);
UINT8 GPIO_READ_PORT_VALUE(UINT8 PORT);

void GPIO_INIT_PIN_DIRECTION(UINT8 PORT ,UINT8 PINno, UINT8 DIRECTION);
void GPIO_WRITE_PIN_VALUE(UINT8 PORT ,UINT8 PINno , UINT8 VALUE);
UINT8 GPIO_READ_PIN_VALUE(UINT8 PORT ,UINT8 PINno);


#endif /* GPIO_H_ */
